/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
      extend: {
          colors: {
              "on-error-container": "#ffb4ab",
              "inverse-surface": "#e2e2e6",
              "error": "#ffb4ab",
              "on-tertiary-fixed": "#2b1700",
              "on-primary": "#ffffff",
              "on-secondary": "#ffffff",
              "surface-variant": "#43474e",
              "on-tertiary-fixed-variant": "#633f0f",
              "on-background": "#e2e2e6",
              "secondary-container": "#3e4759",
              "on-secondary-fixed": "#111c2c",
              "error-container": "#93000a",
              "on-surface-variant": "#c4c6cf",
              "surface": "#0b0e14",
              "surface-tint": "#adc7f7",
              "surface-container-low": "#1a1c22",
              "on-primary-container": "#d6e3ff",
              "tertiary-fixed": "#ffddba",
              "tertiary": "#f2bc82",
              "primary-fixed-dim": "#adc7f7",
              "outline-variant": "#43474e",
              "tertiary-fixed-dim": "#f2bc82",
              "surface-container": "#1e2128",
              "background": "#0b0e14",
              "on-secondary-container": "#d7e2f7",
              "primary": "#adc7f7",
              "tertiary-container": "#633f0f",
              "on-tertiary-container": "#ffddba",
              "on-secondary-fixed-variant": "#3c475a",
              "secondary": "#bfc6dc",
              "secondary-fixed": "#d8e3fa",
              "on-surface": "#e2e2e6",
              "on-error": "#690005",
              "primary-fixed": "#d6e3ff",
              "inverse-on-surface": "#2f3033",
              "surface-container-high": "#282a31",
              "on-primary-fixed-variant": "#2d476f",
              "on-primary-fixed": "#001b3c",
              "primary-container": "#2d476f",
              "outline": "#8e9099",
              "on-tertiary": "#4a2800",
              "secondary-fixed-dim": "#bcc7dd",
              "surface-container-highest": "#33353c",
              "surface-bright": "#37393e",
              "surface-dim": "#111318",
              "surface-container-lowest": "#0b0e14",
              "inverse-primary": "#455f88"
          },
          fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"],
              "manrope": ["Manrope"],
              "inter": ["Inter"]
          },
          borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
